# Exported from Render.com
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: pulse
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
