import type { Place } from "./types";

export const PLACES: Place[] = [
  {
    id: "high-spirits",
    name: "High Spirits",
    type: "now",
    neighborhood: "Koregaon Park",
    address: "North Main Road, Koregaon Park",
    x: 61.6,
    y: 39.1,
    distanceKm: 0.4,
    liveliness: { evening: 88, saturday: 74, late: 36 },
    startsInMinutes: { evening: 12, saturday: 40 },
    blurb: "Live set starting any minute. The room is already loud.",
    hours: "Open · until 1:30 AM",
    friendsNearby: 8,
    cta: "Navigate",
  },
  {
    id: "german-bakery",
    name: "German Bakery",
    type: "table",
    neighborhood: "Koregaon Park",
    address: "North Main Road, KP",
    x: 63.4,
    y: 41.6,
    distanceKm: 0.5,
    liveliness: { evening: 54, saturday: 62, late: 6 },
    queue: { evening: 9, saturday: 14 },
    blurb: "Terrace still turning tables. Breakfast energy, evening light.",
    hours: "Open · until 11:30 PM",
    cta: "Navigate",
  },
  {
    id: "blue-tokai",
    name: "Blue Tokai",
    type: "table",
    neighborhood: "Koregaon Park",
    address: "Lane 7, Koregaon Park",
    x: 64.8,
    y: 38.2,
    distanceKm: 0.7,
    liveliness: { evening: 41, saturday: 48, late: 0 },
    queue: { evening: 4, saturday: 7 },
    blurb: "Last pour-overs of the day. Quiet tables by the window.",
    hours: "Open · until 10:00 PM",
    cta: "Navigate",
  },
  {
    id: "arthurs",
    name: "Arthur’s Theme",
    type: "table",
    neighborhood: "Koregaon Park",
    address: "North Main Road, KP",
    x: 60.4,
    y: 42.6,
    distanceKm: 0.6,
    liveliness: { evening: 63, saturday: 70, late: 8 },
    queue: { evening: 6, saturday: 11 },
    blurb: "European room filling for second seating.",
    hours: "Open · until 11:45 PM",
    friendsNearby: 2,
    cta: "Navigate",
  },
  {
    id: "osho",
    name: "Osho Teerth Garden",
    type: "ground",
    neighborhood: "Koregaon Park",
    address: "Osho, Koregaon Park",
    x: 67.8,
    y: 36.4,
    distanceKm: 0.9,
    liveliness: { evening: 22, saturday: 28, late: 0 },
    blurb: "Garden lights on. Slow walkers, almost no sound.",
    hours: "Closes · 9:00 PM",
    cta: "Navigate",
  },
  {
    id: "prems",
    name: "Prem’s",
    type: "table",
    neighborhood: "Koregaon Park",
    address: "North Main Road, KP",
    x: 59.2,
    y: 38.8,
    distanceKm: 0.5,
    liveliness: { evening: 58, saturday: 66, late: 12 },
    queue: { evening: 5, saturday: 9 },
    blurb: "Garden tables still seating. KP classic, unhurried.",
    hours: "Open · until 12:30 AM",
    cta: "Navigate",
  },
  {
    id: "pottery",
    name: "Clay circle",
    type: "move",
    neighborhood: "Koregaon Park",
    address: "Lane 6 studio, KP",
    x: 65.6,
    y: 43.2,
    distanceKm: 0.8,
    liveliness: { evening: 47, saturday: 22, late: 0 },
    startsInMinutes: { evening: 25 },
    blurb: "Drop-in wheel session. Six wheels left.",
    hours: "Tonight · 9:00–10:30 PM",
    friendsNearby: 1,
    cta: "Join",
  },
  {
    id: "vaishali",
    name: "Vaishali",
    type: "table",
    neighborhood: "FC Road",
    address: "Fergusson College Road",
    x: 40.2,
    y: 61.6,
    distanceKm: 3.1,
    liveliness: { evening: 70, saturday: 92, late: 0 },
    queue: { evening: 16, saturday: 28 },
    blurb: "South Indian room at full tilt. Queue spilling onto FC.",
    hours: "Open · until 11:00 PM",
    cta: "Navigate",
  },
  {
    id: "durga",
    name: "Cafe Durga",
    type: "table",
    neighborhood: "FC Road",
    address: "Fergusson College Road",
    x: 38.8,
    y: 63.4,
    distanceKm: 3.2,
    liveliness: { evening: 66, saturday: 90, late: 0 },
    queue: { evening: 11, saturday: 22 },
    blurb: "Cheese chilli toast still the reason people wait.",
    hours: "Open · until 11:30 PM",
    cta: "Navigate",
  },
  {
    id: "roopali",
    name: "Roopali",
    type: "table",
    neighborhood: "FC Road",
    address: "Fergusson College Road",
    x: 41.4,
    y: 64.8,
    distanceKm: 3.3,
    liveliness: { evening: 61, saturday: 86, late: 0 },
    queue: { evening: 8, saturday: 18 },
    blurb: "Thali line wrapping the verandah.",
    hours: "Open · until 11:00 PM",
    cta: "Navigate",
  },
  {
    id: "wadeshwar",
    name: "Wadeshwar",
    type: "table",
    neighborhood: "FC Road",
    address: "FC Road",
    x: 39.1,
    y: 60.2,
    distanceKm: 3.0,
    liveliness: { evening: 57, saturday: 84, late: 0 },
    queue: { evening: 7, saturday: 15 },
    blurb: "Uttapam coming off the tawa without a pause.",
    hours: "Open · until 11:00 PM",
    cta: "Navigate",
  },
  {
    id: "fc-screening",
    name: "India vs screening",
    type: "now",
    neighborhood: "FC Road",
    address: "Sports bar, FC Road",
    x: 42.2,
    y: 62.6,
    distanceKm: 3.2,
    liveliness: { evening: 80, saturday: 96, late: 18 },
    startsInMinutes: { evening: 8, saturday: 0, late: 0 },
    blurb: "Second innings. Standing room only on the pavement.",
    hours: "Live now",
    friendsNearby: 11,
    cta: "Navigate",
  },
  {
    id: "fc-gig",
    name: "Open mic, FC",
    type: "now",
    neighborhood: "FC Road",
    address: "Cafe basement, FC Road",
    x: 40.8,
    y: 66.2,
    distanceKm: 3.4,
    liveliness: { evening: 52, saturday: 88, late: 24 },
    startsInMinutes: { evening: 35, saturday: 5 },
    blurb: "Acoustic set, twenty people already on the stairs.",
    hours: "Doors open",
    cta: "Join",
  },
  {
    id: "fc-ground",
    name: "FC Road stretch",
    type: "ground",
    neighborhood: "FC Road",
    address: "Fergusson College Road",
    x: 37.6,
    y: 65.8,
    distanceKm: 3.3,
    liveliness: { evening: 48, saturday: 78, late: 10 },
    blurb: "The street itself is the venue tonight.",
    hours: "Always open",
    cta: "Walk it",
  },
  {
    id: "salsa",
    name: "Salsa social",
    type: "move",
    neighborhood: "FC Road",
    address: "Studio above FC Road",
    x: 43.0,
    y: 60.4,
    distanceKm: 3.1,
    liveliness: { evening: 44, saturday: 81, late: 0 },
    startsInMinutes: { evening: 50, saturday: 15 },
    blurb: "Beginner-friendly social. Shoes off at the door.",
    hours: "Tonight · 9:30 PM",
    cta: "Join",
  },
  {
    id: "bedekar",
    name: "Bedekar Misal",
    type: "table",
    neighborhood: "Narayan Peth",
    address: "Narayan Peth, near ABC",
    x: 28.4,
    y: 61.2,
    distanceKm: 4.1,
    liveliness: { evening: 49, saturday: 67, late: 0 },
    queue: { evening: 12, saturday: 20 },
    blurb: "Kolhapuri heat. The line is part of the ritual.",
    hours: "Open · until 10:00 PM",
    cta: "Navigate",
  },
  {
    id: "shabree",
    name: "Shabree",
    type: "table",
    neighborhood: "Deccan",
    address: "Deccan Gymkhana",
    x: 31.6,
    y: 57.4,
    distanceKm: 3.8,
    liveliness: { evening: 55, saturday: 72, late: 0 },
    queue: { evening: 8, saturday: 14 },
    blurb: "Maharashtrian thali, last lot of the evening.",
    hours: "Open · until 10:30 PM",
    cta: "Navigate",
  },
  {
    id: "shaniwar",
    name: "Shaniwar Wada",
    type: "ground",
    neighborhood: "Old City",
    address: "Shaniwar Peth",
    x: 24.8,
    y: 54.6,
    distanceKm: 4.6,
    liveliness: { evening: 31, saturday: 44, late: 0 },
    blurb: "Fort walls lit. Light crowd on the approach.",
    hours: "Closes · 6:30 PM · grounds still walkable",
    cta: "Navigate",
  },
  {
    id: "urban-foundry",
    name: "The Urban Foundry",
    type: "now",
    neighborhood: "Baner",
    address: "Baner Road",
    x: 17.2,
    y: 24.8,
    distanceKm: 7.4,
    liveliness: { evening: 64, saturday: 71, late: 28 },
    startsInMinutes: { evening: 20, saturday: 10 },
    blurb: "DJ already in. Baner’s late room.",
    hours: "Open · until 1:30 AM",
    friendsNearby: 3,
    cta: "Navigate",
  },
  {
    id: "effingut",
    name: "Effingut",
    type: "table",
    neighborhood: "Baner",
    address: "Baner",
    x: 14.6,
    y: 22.4,
    distanceKm: 7.8,
    liveliness: { evening: 50, saturday: 68, late: 22 },
    queue: { evening: 6, saturday: 10, late: 3 },
    blurb: "House beers, a few high-tops left.",
    hours: "Open · until 1:00 AM",
    cta: "Navigate",
  },
  {
    id: "baner-run",
    name: "Baner hill walk",
    type: "move",
    neighborhood: "Baner",
    address: "Baner Pashan trail",
    x: 12.2,
    y: 20.2,
    distanceKm: 8.1,
    liveliness: { evening: 18, saturday: 14, late: 0 },
    blurb: "Last light on the trail. Almost empty.",
    hours: "Daylight",
    cta: "Navigate",
  },
  {
    id: "kayani",
    name: "Kayani Bakery",
    type: "table",
    neighborhood: "Camp",
    address: "East Street, Camp",
    x: 57.2,
    y: 84.6,
    distanceKm: 5.2,
    liveliness: { evening: 12, saturday: 20, late: 0 },
    blurb: "Shutters down. Come back at 7 AM for Shrewsbury.",
    hours: "Closed · opens 7:00 AM",
    cta: "Save",
  },
  {
    id: "east-street",
    name: "East Street night",
    type: "now",
    neighborhood: "Camp",
    address: "East Street, Camp",
    x: 59.4,
    y: 82.2,
    distanceKm: 5.0,
    liveliness: { evening: 46, saturday: 64, late: 32 },
    blurb: "Neon, bargains, and a crowd that doesn’t check the clock.",
    hours: "Late",
    cta: "Navigate",
  },
  {
    id: "mg-road",
    name: "MG Road",
    type: "ground",
    neighborhood: "Camp",
    address: "Mahatma Gandhi Road",
    x: 54.6,
    y: 80.4,
    distanceKm: 4.8,
    liveliness: { evening: 38, saturday: 55, late: 16 },
    blurb: "Camp’s spine. A few shops still lit.",
    hours: "Always open",
    cta: "Walk it",
  },
  {
    id: "phoenix-pop",
    name: "Phoenix pop-up",
    type: "now",
    neighborhood: "Viman Nagar",
    address: "Phoenix Marketcity",
    x: 91.2,
    y: 41.6,
    distanceKm: 6.8,
    liveliness: { evening: 72, saturday: 80, late: 0 },
    startsInMinutes: { evening: 18, saturday: 5 },
    blurb: "Independent labels, one-night rack. Third floor.",
    hours: "Until 10:00 PM",
    cta: "Navigate",
  },
  {
    id: "kalyani-set",
    name: "Kalyani terrace set",
    type: "now",
    neighborhood: "Kalyani Nagar",
    address: "Kalyani Nagar",
    x: 82.6,
    y: 29.4,
    distanceKm: 3.6,
    liveliness: { evening: 69, saturday: 77, late: 40 },
    startsInMinutes: { evening: 22, saturday: 8 },
    blurb: "House DJ, river on one side. Not advertised.",
    hours: "Until 1:00 AM",
    friendsNearby: 4,
    cta: "Navigate",
  },
  {
    id: "bund",
    name: "Bund Garden",
    type: "ground",
    neighborhood: "Bund Garden",
    address: "Bund Garden Road",
    x: 58.2,
    y: 48.6,
    distanceKm: 1.6,
    liveliness: { evening: 26, saturday: 34, late: 5 },
    blurb: "River air. A handful of walkers left.",
    hours: "Open",
    cta: "Navigate",
  },
  {
    id: "boardgames",
    name: "Boardgame table",
    type: "move",
    neighborhood: "Aundh",
    address: "Cafe, Aundh",
    x: 33.4,
    y: 17.8,
    distanceKm: 6.9,
    liveliness: { evening: 36, saturday: 42, late: 8 },
    startsInMinutes: { evening: 15, saturday: 40 },
    blurb: "Open table, Catan still in the box.",
    hours: "Until 11:00 PM",
    cta: "Join",
  },
  {
    id: "mocha",
    name: "Mocha",
    type: "table",
    neighborhood: "JM Road",
    address: "Jangli Maharaj Road",
    x: 44.8,
    y: 58.2,
    distanceKm: 2.8,
    liveliness: { evening: 43, saturday: 60, late: 14 },
    queue: { evening: 3, saturday: 6 },
    blurb: "Hookah terrace thinning out, still a few sofas.",
    hours: "Open · until 12:30 AM",
    cta: "Navigate",
  },
  {
    id: "river-walk",
    name: "Riverfront walk",
    type: "move",
    neighborhood: "Koregaon Park",
    address: "Mutha river path",
    x: 70.2,
    y: 40.8,
    distanceKm: 1.1,
    liveliness: { evening: 29, saturday: 24, late: 7 },
    blurb: "Lit path along the water. Easy pace.",
    hours: "Always open",
    cta: "Walk it",
  },
];
